language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
env:
  - DB=mysql

matrix:
    include:
        - php: 5.4
          env: DB=postgres
        - php: 5.4
          env: DB=sqlite
    allow_failures:
        - php: hhvm

sudo: false

cache:
  directories:
    - vendors
    - $HOME/.composer/cache

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add travis.php.ini; fi;
  - |
    bash -c "if [ '$DB' == 'mysql' ]; then
    mysql -u root -e \"CREATE DATABASE basercms CHARACTER SET utf8;\";
    mysql -u root -e \"GRANT ALL PRIVILEGES ON basercms.* TO basercms@localhost IDENTIFIED BY 'basercms';\";
    fi;"
  - |
    bash -c "if [ '$DB' == 'postgres' ]; then
    psql -U postgres -c \"CREATE USER basercms WITH PASSWORD 'basercms';\";
    psql -U postgres -c \"CREATE DATABASE basercms OWNER basercms ENCODING='utf8'\";
    fi;"
  - if [ "$TRAVIS_PHP_VERSION" != "5.2" ]; then composer self-update; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "5.2" ] && [ -n "$GITHUB_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_TOKEN}; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "5.2" ]; then composer install --dev; fi;
  - cd app
  - php ./Console/cake.php bc_manager checkenv
  - php ./Console/cake.php bc_manager install "http://localhost" "$DB" "admin" "basercms" "webmaster@example.org" --host "localhost" --database "basercms" --login "basercms" --password "basercms" --prefix "mysite_" --data "nada-icons.default"

script:
  - php ./Console/cake.php baser_test baser BcAll

notifications:
  email: false
